import { Category, ServiceType } from './types';

export const SERVICE_TYPES: ServiceType[] = [
  { id: 'inicio_actividades', name: 'Inicio de Actividades', description: 'Altas, cambios y bajas', icon: '🚀' },
  { id: 'iva', name: 'IVA', description: 'Declaraciones mensuales', icon: '🧾' },
  { id: 'renta', name: 'Renta', description: 'Declaración anual', icon: '📊' },
  { id: 'contabilidad', name: 'Contabilidad', description: 'Balances, estados', icon: '📈' },
  { id: 'nomina', name: 'Nómina', description: 'Liquidaciones, contratos', icon: '👥' },
  { id: 'regularizacion', name: 'Regularización', description: 'Rectificaciones', icon: '✅' },
];

export const CATEGORIES: Category[] = [
  { id: 'bienvenida', name: 'Bienvenida', icon: '👋', color: 'bg-green-600', colorHex: '#16a34a', description: 'Saludos y primer contacto' },
  { id: 'menu', name: 'Menú Principal', icon: '📋', color: 'bg-blue-600', colorHex: '#2563eb', description: 'Opciones del menú interactivo' },
  { id: 'servicios', name: 'Servicios', icon: '💼', color: 'bg-indigo-600', colorHex: '#4f46e5', description: 'Información de servicios' },
  { id: 'documentos', name: 'Documentos', icon: '📄', color: 'bg-orange-600', colorHex: '#ea580c', description: 'Solicitud y envío de docs' },
  { id: 'tramites', name: 'Trámites', icon: '🏢', color: 'bg-purple-600', colorHex: '#9333ea', description: 'Trámites específicos' },
  { id: 'cobranza', name: 'Cobranza', icon: '💳', color: 'bg-red-600', colorHex: '#dc2626', description: 'Recordatorios y cobros' },
  { id: 'general', name: 'General', icon: '💬', color: 'bg-slate-600', colorHex: '#475569', description: 'Mensajes generales' },
];

export const DEFAULT_TEMPLATES = [
  {
    id: 'bienvenida_cliente',
    name: 'Saludo Cliente',
    content: 'Hola 👋 Bienvenido a MTZ Consultores Tributarios. ¿En qué podemos ayudarte hoy?',
    category: 'bienvenida',
    segment: 'cliente',
    is_active: true,
    priority: 1,
    trigger: 'hola',
    actions: [
      { type: 'button', id: 'btn_docs', title: '📄 Ver mis documentos', next_template_id: 'menu_cliente' },
      { type: 'button', id: 'btn_iva', title: '🧾 IVAs', next_template_id: 'tramite_iva_info' },
      { type: 'button', id: 'btn_solicitudes', title: '🔎 Mis solicitudes', next_template_id: 'solicitudes_info' },
      { type: 'button', id: 'btn_asesor', title: '📞 Asesor', next_template_id: 'derivacion_asesor' },
    ],
  },
  {
    id: 'bienvenida_prospecto',
    name: 'Saludo Prospecto',
    content: '¡Hola! 👋 Bienvenido a MTZ Consultores. ¿En qué podemos ayudarte?',
    category: 'bienvenida',
    segment: 'prospecto',
    is_active: true,
    priority: 1,
    trigger: 'hola',
    actions: [
      { type: 'button', id: 'btn_cotizar', title: '💼 Cotizar', next_template_id: 'menu_prospecto' },
      { type: 'button', id: 'btn_info', title: '📝 Información', next_template_id: 'servicios_general' },
      { type: 'button', id: 'btn_estado', title: '🔎 Estado', next_template_id: 'derivacion_asesor' },
    ],
  },
  {
    id: 'menu_cliente',
    name: 'Menú Cliente',
    content: '¿Qué necesitas?',
    category: 'menu',
    segment: 'cliente',
    is_active: true,
    priority: 10,
    actions: [
      { type: 'button', id: 'btn_docs', title: '📄 Mis Documentos', next_template_id: 'doc_solicitar' },
      { type: 'button', id: 'btn_iva', title: '🧾 IVAs', next_template_id: 'tramite_iva_info' },
      { type: 'button', id: 'btn_solicitudes', title: '🔎 Mis Solicitudes', next_template_id: 'solicitudes_info' },
      { type: 'button', id: 'btn_asesor', title: '📞 Asesor', next_template_id: 'derivacion_asesor' },
    ],
  },
  {
    id: 'menu_prospecto',
    name: 'Menú Prospecto',
    content: '¿En qué podemos ayudarte?',
    category: 'menu',
    segment: 'prospecto',
    is_active: true,
    priority: 10,
    actions: [
      { type: 'button', id: 'btn_cotizar', title: '💼 Cotizar', next_template_id: 'derivacion_asesor' },
      { type: 'button', id: 'btn_info', title: '📝 Información', next_template_id: 'servicios_general' },
      { type: 'button', id: 'btn_estado', title: '🔎 Estado', next_template_id: 'derivacion_asesor' },
      { type: 'button', id: 'btn_asesor', title: '📞 Asesor', next_template_id: 'derivacion_asesor' },
    ],
  },
  {
    id: 'servicios_general',
    name: 'Lista de Servicios',
    content: 'Nuestros servicios:\n\n🚀 Inicio de Actividades\n🧾 IVA\n📊 Renta\n📈 Contabilidad\n👥 Nómina\n✅ Regularizaciones',
    category: 'servicios',
    segment: 'todos',
    is_active: true,
    priority: 20,
    actions: [],
  },
  {
    id: 'tramite_iva_info',
    name: 'Info IVA',
    content: '🧾 *Servicio de IVA*\n\n• Declaración mensual (Formulario 29)\n• Recuperación de IVA\n• Asesoramiento\n\n¿Qué necesitas ver?',
    category: 'tramites',
    service_type: 'iva',
    segment: 'todos',
    is_active: true,
    priority: 30,
    actions: [
      { type: 'button', id: 'btn_iva_mar2026', title: '🧾 Marzo 2026' },
      { type: 'button', id: 'btn_iva_feb2026', title: '🧾 Febrero 2026' },
      { type: 'button', id: 'btn_iva_solicitar', title: '📋 Solicitar IVA' },
    ],
  },
  {
    id: 'tramite_renta_info',
    name: 'Info Renta',
    content: '📊 *Declaración de Renta*\n\n• Declaración anual (F22)\n• Optimización\n• Pérdidas tributarias',
    category: 'tramites',
    service_type: 'renta',
    segment: 'todos',
    is_active: true,
    priority: 30,
    actions: [],
  },
  {
    id: 'doc_solicitar',
    name: 'Solicitar Documentos',
    content: 'Para continuar, necesito:\n\n✓ RUT actualizado\n✓ Última declaración de renta\n✓ Balance último mes',
    category: 'documentos',
    segment: 'todos',
    is_active: true,
    priority: 25,
    actions: [],
  },
  {
    id: 'cobranza_recordatorio',
    name: 'Recordatorio Pago',
    content: 'Estimado cliente, te recordamos que tu pago está pendiente. Por favor regularice a la brevedad.',
    category: 'cobranza',
    segment: 'cliente',
    is_active: true,
    priority: 40,
    trigger: 'pago',
    actions: [],
  },
  {
    id: 'derivacion_asesor',
    name: 'Derivación a Asesor',
    content: 'Tu consulta requiere atención especializada. Un asesor de MTZ se comunicará contigo a la brevedad.',
    category: 'general',
    segment: 'todos',
    is_active: true,
    priority: 50,
    actions: [],
  },
  {
    id: 'confirmacion_recepcion',
    name: 'Confirmación Recepción',
    content: '✅ Hemos recibido tus documentos correctamente. Los revisaremos y te contactaremos en 24 horas.',
    category: 'general',
    segment: 'todos',
    is_active: true,
    priority: 15,
    actions: [],
  },
  {
    id: 'gracias',
    name: 'Mensaje de Cierre',
    content: '¡Gracias por contactar MTZ Consultores! 👋\n\nSi tienes más dudas, escríbenos cuando quieras.\n\nEquipo MTZ',
    category: 'general',
    segment: 'todos',
    is_active: true,
    priority: 100,
    actions: [],
  },
  {
    id: 'solicitudes_info',
    name: 'Mis Solicitudes',
    content: 'Para consultar una solicitud, envía el código que te dimos. Ejemplo: DOC-1234',
    category: 'general',
    segment: 'cliente',
    is_active: true,
    priority: 35,
    actions: [],
  },
];

export function getCategoryInfo(catId: string): Category {
  return CATEGORIES.find(c => c.id === catId) || CATEGORIES[6];
}

export function getServiceInfo(serviceId?: string): ServiceType | undefined {
  return SERVICE_TYPES.find(s => s.id === serviceId);
}
